AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-s3-thumbnail

Parameters:
  AppBucketName:
    Type: String
    Description: "REQUIRED: Unique S3 bucket name to use for the app."

Resources:
  S4VideoThumbnail:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/handler.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          IMAGE_WIDTH: 300
          IMAGE_HEIGHT: 300
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref AppBucketName
        - S3WritePolicy:
            BucketName: !Ref AppBucketName
      Layers:
        - arn:aws:lambda:us-east-1:************:layer:ffmpeg:1
      Events:
        S3NewObjectEvent:
          Type: S3
          Properties:
            Bucket: !Ref AppBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: "videos/"
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AppBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt S4VideoThumbnail.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: "videos/"
